#!/usr/bin/env bash

function BuildPackage {
  echo "Building package..."
  cd /workspaces/pypi_krisinformation
  python krisinformation/setup.py sdist
  echo "Package built!"
}

function UploadPackage {
  echo "Building package..."
  twine upload /workspaces/pypi_krisinformation/dist/*
  echo "Package built!"
}

